-- 1. Crear la tabla de caché de búsquedas
create table if not exists search_cache (
  id bigint generated by default as identity primary key,
  query text unique not null,
  results jsonb not null,
  hits int default 1,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Habilitar seguridad (opcional, si quieres que sea pública puedes saltar esto o usar policies)
alter table search_cache enable row level security;

-- 3. Política: Cualquiera puede LEER la caché
create policy "Public Cache Read"
on search_cache for select
using ( true );

-- 4. Política: Cualquiera (anon) puede INSERTAR en caché (para guardar nuevos resultados)
-- Nota: En producción idealmente esto lo haría solo el Backend con Service Role,
-- pero para este MVP dejamos que 'anon' inserte si usas la Key pública.
create policy "Public Cache Insert"
on search_cache for insert
with check ( true );

-- 5. Crear índice para búsquedas rápidas
create index search_cache_query_idx on search_cache (query);
